export const LANGUAGES = ['fr', 'en']
export const DEFAULT_MIN_PRICE = 0
export const DEFAULT_MAX_PRICE = 10000
export const LOCAL_STORAGE_SEARCH = 'map-search'
export const PER_PAGE = 30
export const BASE = 'base'
export const SM = 'sm'
export const MD = 'md'
export const LG = 'lg'
export const XL = 'xl'
