export const data = [
  {
    title: 'Big 4 bedrooms with windows, 2 bathrooms-Mc Gill campus',
    description:
      '3753 COLONIALE, H2W 2B5 Move in Ready. BIG BRIGHT APARTMENT WITH PANORAMIC VIEW OF THE CITY. 3RD ...',
    date: '2021-03-24T18:53:43.000Z',
    image:
      'https://i.ebayimg.com/00/s/NDUwWDgwMA==/z/aukAAOSwGcRgW4md/$_57.JPG',
    images: [
      'https://i.ebayimg.com/00/s/NDUwWDgwMA==/z/aukAAOSwGcRgW4md/$_57.JPG',
      'https://i.ebayimg.com/00/s/NDUwWDgwMA==/z/lUUAAOSwD89gW4o8/$_57.JPG',
      'https://i.ebayimg.com/00/s/NDUwWDgwMA==/z/uzIAAOSw6UxgW4mj/$_57.JPG',
      'https://i.ebayimg.com/00/s/NDUwWDgwMA==/z/djIAAOSwog9gW4mm/$_57.JPG',
      'https://i.ebayimg.com/00/s/NDUwWDgwMA==/z/4icAAOSwx-9gW4nJ/$_57.JPG',
      'https://i.ebayimg.com/00/s/NDUwWDgwMA==/z/LzMAAOSw1zJgW4nC/$_57.JPG',
      'https://i.ebayimg.com/00/s/NDUwWDgwMA==/z/yxUAAOSw~5VgW4mZ/$_57.JPG',
      'https://i.ebayimg.com/00/s/ODAwWDQ1MA==/z/mjIAAOSwZFNgW4oo/$_57.JPG',
      'https://i.ebayimg.com/00/s/ODAwWDQ1MA==/z/bSwAAOSwLPJgW4nM/$_57.JPG',
      'https://i.ebayimg.com/00/s/NDUwWDgwMA==/z/eSoAAOSwOCVgW4mg/$_57.JPG',
    ],
    attributes: {
      forrentbyhousing: 'ownr',
      unittype: 'apartment',
      numberbedrooms: 4,
      numberbathrooms: 20,
      agreementtype: 'one-year',
      dateavailable: '2021-08-01T00:00:00.000Z',
      petsallowed: 0,
      areainfeet: 1200,
      furnished: 0,
      laundryinunit: 0,
      laundryinbuilding: 0,
      dishwasher: 0,
      fridgefreezer: 0,
      airconditioning: 0,
      yard: 0,
      balcony: 1,
      smokingpermitted: 0,
      gym: 0,
      pool: 0,
      concierge: 0,
      twentyfourhoursecurity: 0,
      bicycleparking: 0,
      storagelocker: 0,
      elevator: 0,
      wheelchairaccessible: 0,
      braillelabels: 0,
      audioprompts: 0,
      barrierfreeentrancesandramps: 0,
      visualaids: 0,
      accessiblewashroomsinsuite: 0,
      hydro: 0,
      heat: 0,
      water: 0,
      cabletv: 0,
      internet: 0,
      numberparkingspots: 0,
      price: 2325,
      location: '3753 Avenue Coloniale, Montréal, QC H2W 2B5, Canada',
      type: 'OFFERED',
      coordinates: [-73.574355, 45.516152],
    },
    url:
      'https://www.kijiji.ca/v-appartement-condo/ville-de-montreal/big-4-bedrooms-with-windows-2-bathrooms-mc-gill-campus/1557297088',
  },
  {
    title: '3 BEDROOM APARTMENT VICTORIA VILLAGE',
    description:
      '339 Victoria #7 Available August 1st 3 bedrooms $1600 Hot water include dinner Balcony Stove ...',
    date: '2021-03-24T18:51:25.000Z',
    image:
      'https://i.ebayimg.com/00/s/MzQyWDUxMg==/z/llMAAOSwMq9gW4n8/$_57.JPG',
    images: [
      'https://i.ebayimg.com/00/s/MzQyWDUxMg==/z/llMAAOSwMq9gW4n8/$_57.JPG',
      'https://i.ebayimg.com/00/s/MzQyWDUxMg==/z/0pYAAOSw~OpgW4n-/$_57.JPG',
      'https://i.ebayimg.com/00/s/MzQyWDUxMg==/z/spMAAOSw8AdgW4n~/$_57.JPG',
      'https://i.ebayimg.com/00/s/MzQ1WDUxMg==/z/c4wAAOSw8kFgW4oA/$_57.JPG',
      'https://i.ebayimg.com/00/s/MzQyWDUxMg==/z/YeEAAOSwxoNgW4oM/$_57.JPG',
      'https://i.ebayimg.com/00/s/MzQyWDUxMg==/z/W4EAAOSwYdBgW4oN/$_57.JPG',
      'https://i.ebayimg.com/00/s/MzQyWDUxMg==/z/5mMAAOSwRwxgW4oP/$_57.JPG',
      'https://i.ebayimg.com/00/s/MzQyWDUxMg==/z/NSYAAOSwawZgW4oQ/$_57.JPG',
      'https://i.ebayimg.com/00/s/MzQzWDUxMg==/z/ZU4AAOSwSEhgW4od/$_57.JPG',
      'https://i.ebayimg.com/00/s/MzQyWDUxMg==/z/LsYAAOSw0iFgW4oi/$_57.JPG',
    ],
    attributes: {
      forrentbyhousing: 'ownr',
      unittype: 'apartment',
      numberbedrooms: 3,
      numberbathrooms: 10,
      agreementtype: 'one-year',
      dateavailable: '2021-08-01T00:00:00.000Z',
      petsallowed: 'limited',
      areainfeet: 900,
      furnished: 0,
      laundryinunit: 0,
      laundryinbuilding: 1,
      dishwasher: 0,
      fridgefreezer: 1,
      airconditioning: 0,
      yard: 0,
      balcony: 1,
      smokingpermitted: 2,
      gym: 0,
      pool: 0,
      concierge: 0,
      twentyfourhoursecurity: 0,
      bicycleparking: 0,
      storagelocker: 0,
      elevator: 0,
      wheelchairaccessible: 0,
      braillelabels: 0,
      audioprompts: 0,
      barrierfreeentrancesandramps: 0,
      visualaids: 0,
      accessiblewashroomsinsuite: 0,
      hydro: 0,
      heat: 0,
      water: 1,
      cabletv: 0,
      internet: 0,
      numberparkingspots: 0,
      rentalsvirtualoptions: 'onlineapplicationvideochatvirtualtour',
      price: 1600,
      location: '7-339 Avenue Victoria, Westmount, QC H3Z 2N1, Canada',
      type: 'OFFERED',
      coordinates: [-73.649151, 45.499628],
    },
    url:
      'https://www.kijiji.ca/v-appartement-condo/ville-de-montreal/3-bedroom-apartment-victoria-village/1557296597',
  },
  {
    title: 'SUPERBE HAUT DUPLEX + BALCON ENSOLEILLÉ TT MEUBLÉ PLATEAU-MÉTRO',
    description:
      'SUPERBE HAUT DE DUPLEX TT MEUBLÉ & TT INCLUS+ BALCON : PLATEAU-H2W2K2 &&& SVP : Si intéressé(s), se ...',
    date: '2021-03-24T18:48:50.000Z',
    image:
      'https://i.ebayimg.com/00/s/ODAwWDQ1MA==/z/KTAAAOSwBQtgW4ke/$_57.JPG',
    images: [
      'https://i.ebayimg.com/00/s/ODAwWDQ1MA==/z/KTAAAOSwBQtgW4ke/$_57.JPG',
      'https://i.ebayimg.com/00/s/ODAwWDQ1MA==/z/BTYAAOSwlVpgW4kp/$_57.JPG',
      'https://i.ebayimg.com/00/s/NTk4WDgwMA==/z/b7oAAOSwWPRgW4k1/$_57.JPG',
      'https://i.ebayimg.com/00/s/NTk4WDgwMA==/z/s10AAOSw6wdgW4kv/$_57.JPG',
      'https://i.ebayimg.com/00/s/NTk4WDgwMA==/z/ZuAAAOSwYS5gW4k9/$_57.JPG',
      'https://i.ebayimg.com/00/s/NTk4WDgwMA==/z/clkAAOSwMWFgW4lD/$_57.JPG',
      'https://i.ebayimg.com/00/s/NTk4WDgwMA==/z/5a0AAOSwcbVgW4lV/$_57.JPG',
      'https://i.ebayimg.com/00/s/NTk4WDgwMA==/z/lKoAAOSw1btgW4lH/$_57.JPG',
      'https://i.ebayimg.com/00/s/NTEyWDM4NA==/z/8tAAAOSwsspgW4kr/$_57.JPG',
      'https://i.ebayimg.com/00/s/ODAwWDU5OA==/z/C6QAAOSwFHFgW4l~/$_57.JPG',
    ],
    attributes: {
      forrentbyhousing: 'ownr',
      unittype: 'apartment',
      numberbedrooms: 2,
      numberbathrooms: 10,
      agreementtype: 'one-year',
      dateavailable: '2021-05-01T00:00:00.000Z',
      petsallowed: 0,
      areainfeet: 700,
      furnished: 1,
      laundryinunit: 1,
      laundryinbuilding: 0,
      dishwasher: 0,
      fridgefreezer: 1,
      airconditioning: 1,
      yard: 0,
      balcony: 1,
      smokingpermitted: 2,
      gym: 0,
      pool: 0,
      concierge: 0,
      twentyfourhoursecurity: 0,
      bicycleparking: 0,
      storagelocker: 0,
      elevator: 0,
      wheelchairaccessible: 0,
      braillelabels: 0,
      audioprompts: 0,
      barrierfreeentrancesandramps: 0,
      visualaids: 0,
      accessiblewashroomsinsuite: 0,
      hydro: 1,
      heat: 1,
      water: 1,
      cabletv: 0,
      internet: 1,
      numberparkingspots: 0,
      price: 1500,
      location: 'Avenue Henri-Julien, Montréal, QC H2W 2K2, Canada',
      type: 'OFFERED',
      coordinates: [-73.607378, 45.533252],
    },
    url:
      'https://www.kijiji.ca/v-appartement-condo/ville-de-montreal/superbe-haut-duplex-balcon-ensoleille-tt-meuble-plateau-metro/1557296147',
  },
  {
    title: 'Grand 3½/Eau chaude/Poêle-Frigo inclus/Métro Pie-XI',
    description:
      'Tel: 514-952-0497 Contacter l’agent de location directement par téléphone. Pas de COURRIEL, pas de ...',
    date: '2021-03-16T17:02:55.000Z',
    image:
      'https://i.ebayimg.com/00/s/NjAwWDgwMA==/z/ubQAAOSw91NgUOS9/$_57.JPG',
    images: [
      'https://i.ebayimg.com/00/s/NjAwWDgwMA==/z/ubQAAOSw91NgUOS9/$_57.JPG',
      'https://i.ebayimg.com/00/s/NjAwWDgwMA==/z/1-oAAOSwjhZgUOS2/$_57.JPG',
      'https://i.ebayimg.com/00/s/NjAwWDgwMA==/z/Y0QAAOSw6udgUOeX/$_57.JPG',
      'https://i.ebayimg.com/00/s/NjAwWDgwMA==/z/nwkAAOSwsTxgUOcl/$_57.JPG',
      'https://i.ebayimg.com/00/s/NjAwWDgwMA==/z/W9oAAOSwHWJgUOe~/$_57.JPG',
      'https://i.ebayimg.com/00/s/ODAwWDYwMA==/z/0~UAAOSwOzxgUOiH/$_57.JPG',
      'https://i.ebayimg.com/00/s/ODAwWDYwMA==/z/yFEAAOSwCUNgUOem/$_57.JPG',
      'https://i.ebayimg.com/00/s/ODAwWDYwMA==/z/nqgAAOSwkmVgUOey/$_57.JPG',
      'https://i.ebayimg.com/00/s/ODAwWDYwMA==/z/uI4AAOSwmt1gUOes/$_57.JPG',
      'https://i.ebayimg.com/00/s/ODAwWDYwMA==/z/EFYAAOSwHYBgUOcW/$_57.JPG',
      'https://i.ebayimg.com/00/s/ODAwWDYwMA==/z/wcIAAOSwMz1gUOcM/$_57.JPG',
      'https://i.ebayimg.com/00/s/NjAwWDgwMA==/z/VMYAAOSw8bhgUOiY/$_57.JPG',
      'https://i.ebayimg.com/00/s/NjAwWDgwMA==/z/k9oAAOSwFdRgUOip/$_57.JPG',
      'https://i.ebayimg.com/00/s/ODAwWDYwMA==/z/p88AAOSwNzJgUOic/$_57.JPG',
      'https://i.ebayimg.com/00/s/NjAwWDgwMA==/z/QDoAAOSwbuFgUOkK/$_57.JPG',
      'https://i.ebayimg.com/00/s/ODAwWDYwMA==/z/BF4AAOSwUuRgUOSc/$_57.JPG',
      'https://i.ebayimg.com/00/s/NTEzWDgwMA==/z/Kl0AAOSwEbhgUOSA/$_57.JPG',
      'https://i.ebayimg.com/00/s/NDcxWDgwMA==/z/cRIAAOSw7ctgUOZD/$_57.JPG',
      'https://i.ebayimg.com/00/s/ODAwWDgwMA==/z/ohMAAOSwQuFgUOSF/$_57.JPG',
    ],
    attributes: {
      forrentbyhousing: 'reprofessional',
      unittype: 'apartment',
      numberbedrooms: 1.5,
      numberbathrooms: 35,
      agreementtype: 'one-year',
      dateavailable: '2021-07-01T00:00:00.000Z',
      petsallowed: 'limited',
      areainfeet: 700,
      furnished: 0,
      laundryinunit: 0,
      laundryinbuilding: 1,
      dishwasher: 0,
      fridgefreezer: 0,
      airconditioning: 1,
      yard: 0,
      balcony: 1,
      smokingpermitted: 2,
      gym: 0,
      pool: 0,
      concierge: 1,
      twentyfourhoursecurity: 1,
      bicycleparking: 0,
      storagelocker: 0,
      elevator: 0,
      wheelchairaccessible: 0,
      braillelabels: 0,
      audioprompts: 0,
      barrierfreeentrancesandramps: 0,
      visualaids: 0,
      accessiblewashroomsinsuite: 0,
      hydro: 0,
      heat: 0,
      water: 1,
      cabletv: 0,
      internet: 0,
      numberparkingspots: 0,
      price: 925,
      location: '5910 21e Avenue, Montréal, QC H1X 1L9, Canada',
      type: 'OFFERED',
      coordinates: [-73.574975, 45.560202],
    },
    url:
      'https://www.kijiji.ca/v-appartement-condo/ville-de-montreal/grand-3-eau-chaude-poele-frigo-inclus-metro-pie-xi/1555874944',
  },
  {
    title: '3½/Eau chaude/Entré Laveuse-Sécheuse/Dernier étage',
    description:
      'Tel: 514-952-0497 Contacter l’agent de location directement par téléphone. Pas de COURRIEL, pas de ...',
    date: '2021-03-22T22:27:49.000Z',
    image:
      'https://i.ebayimg.com/00/s/ODAwWDYwMA==/z/el4AAOSwe5lgWRkW/$_57.JPG',
    images: [
      'https://i.ebayimg.com/00/s/ODAwWDYwMA==/z/el4AAOSwe5lgWRkW/$_57.JPG',
      'https://i.ebayimg.com/00/s/NjAwWDgwMA==/z/qDMAAOSwznxgWRki/$_57.JPG',
      'https://i.ebayimg.com/00/s/NjAwWDgwMA==/z/9-YAAOSw6xdgWRk5/$_57.JPG',
      'https://i.ebayimg.com/00/s/NjAwWDgwMA==/z/3eUAAOSwbf9gWRsP/$_57.JPG',
      'https://i.ebayimg.com/00/s/ODAwWDYwMA==/z/X1EAAOSwn-dgWRkm/$_57.JPG',
      'https://i.ebayimg.com/00/s/NjAwWDgwMA==/z/vpQAAOSwikNgWRkq/$_57.JPG',
      'https://i.ebayimg.com/00/s/NjAwWDgwMA==/z/F8UAAOSw5NFgWRsF/$_57.JPG',
      'https://i.ebayimg.com/00/s/NjAwWDgwMA==/z/ydQAAOSwzXJgWRoR/$_57.JPG',
      'https://i.ebayimg.com/00/s/NjAwWDgwMA==/z/SgQAAOSwpMlgWRoY/$_57.JPG',
      'https://i.ebayimg.com/00/s/NjAwWDgwMA==/z/sm8AAOSwwCpgWRkx/$_57.JPG',
      'https://i.ebayimg.com/00/s/NjAwWDgwMA==/z/5hgAAOSwa0BgWRpr/$_57.JPG',
      'https://i.ebayimg.com/00/s/NjAwWDgwMA==/z/u7UAAOSwxb5gWRp-/$_57.JPG',
      'https://i.ebayimg.com/00/s/NjAwWDgwMA==/z/u7wAAOSwxb5gWRqB/$_57.JPG',
      'https://i.ebayimg.com/00/s/ODAwWDYwMA==/z/ZjcAAOSwUJtgWRqX/$_57.JPG',
      'https://i.ebayimg.com/00/s/ODAwWDYwMA==/z/8AgAAOSwJgBgWRr~/$_57.JPG',
      'https://i.ebayimg.com/00/s/ODAwWDYwMA==/z/tVkAAOSw7hZgWRsC/$_57.JPG',
      'https://i.ebayimg.com/00/s/ODAwWDYwMA==/z/sxoAAOSw~AhgWRs9/$_57.JPG',
      'https://i.ebayimg.com/00/s/ODAwWDYwMA==/z/0iUAAOSwm5NgWRtG/$_57.JPG',
      'https://i.ebayimg.com/00/s/ODAwWDQ1MA==/z/amYAAOSwpKJgWRtN/$_57.JPG',
      'https://i.ebayimg.com/00/s/NTE2WDgwMA==/z/-fkAAOSw6xdgWRtK/$_57.JPG',
    ],
    attributes: {
      forrentbyhousing: 'reprofessional',
      unittype: 'apartment',
      numberbedrooms: 1,
      numberbathrooms: 10,
      agreementtype: 'one-year',
      dateavailable: '2021-07-01T00:00:00.000Z',
      petsallowed: 'limited',
      areainfeet: 600,
      furnished: 0,
      laundryinunit: 1,
      laundryinbuilding: 0,
      dishwasher: 0,
      fridgefreezer: 0,
      airconditioning: 0,
      yard: 0,
      balcony: 1,
      smokingpermitted: 2,
      gym: 0,
      pool: 0,
      concierge: 1,
      twentyfourhoursecurity: 1,
      bicycleparking: 0,
      storagelocker: 0,
      elevator: 0,
      wheelchairaccessible: 0,
      braillelabels: 0,
      audioprompts: 0,
      barrierfreeentrancesandramps: 0,
      visualaids: 0,
      accessiblewashroomsinsuite: 0,
      hydro: 0,
      heat: 0,
      water: 1,
      cabletv: 0,
      internet: 0,
      numberparkingspots: 0,
      price: 915,
      location: '5955 25e Avenue, Montréal, QC H1T 3L3, Canada',
      type: 'OFFERED',
      coordinates: [-73.573402, 45.563063],
    },
    url:
      'https://www.kijiji.ca/v-appartement-condo/ville-de-montreal/3-eau-chaude-entre-laveuse-secheuse-dernier-etage/1556988590',
  },
  {
    title: '2½/Eau chaude incluse/Dernier étage/25e Avenue et Rosemont',
    description:
      'Tel: 514-952-0497 Contacter l’agent de location directement par téléphone. Pas de COURRIEL, pas de ...',
    date: '2021-03-22T22:43:58.000Z',
    image:
      'https://i.ebayimg.com/00/s/ODAwWDYwMA==/z/GzAAAOSw2eFgWR02/$_57.JPG',
    images: [
      'https://i.ebayimg.com/00/s/ODAwWDYwMA==/z/GzAAAOSw2eFgWR02/$_57.JPG',
      'https://i.ebayimg.com/00/s/NjAwWDgwMA==/z/z3gAAOSwHIFgWR0O/$_57.JPG',
      'https://i.ebayimg.com/00/s/ODAwWDYwMA==/z/eIAAAOSwzXJgWR0e/$_57.JPG',
      'https://i.ebayimg.com/00/s/NjAwWDgwMA==/z/wVoAAOSw24VgWR0g/$_57.JPG',
      'https://i.ebayimg.com/00/s/NjAwWDgwMA==/z/gXcAAOSw-UlgWR0z/$_57.JPG',
      'https://i.ebayimg.com/00/s/ODAwWDYwMA==/z/wLcAAOSw8T9gWR04/$_57.JPG',
      'https://i.ebayimg.com/00/s/NjAwWDgwMA==/z/wqcAAOSwDU5gWR07/$_57.JPG',
      'https://i.ebayimg.com/00/s/NjAwWDgwMA==/z/r0QAAOSwz21gWR1B/$_57.JPG',
      'https://i.ebayimg.com/00/s/NTE2WDgwMA==/z/8coAAOSwJgBgWRzv/$_57.JPG',
      'https://i.ebayimg.com/00/s/ODAwWDQ1MA==/z/6KcAAOSwVa1gWRzx/$_57.JPG',
      'https://i.ebayimg.com/00/s/ODAwWDYwMA==/z/Tc4AAOSwCZZgWRzs/$_57.JPG',
      'https://i.ebayimg.com/00/s/NjAwWDgwMA==/z/4MoAAOSwz71gWR0G/$_57.JPG',
      'https://i.ebayimg.com/00/s/ODAwWDgwMA==/z/kwAAAOSw~kJgWR2d/$_57.JPG',
    ],
    attributes: {
      forrentbyhousing: 'reprofessional',
      unittype: 'apartment',
      numberbedrooms: 0,
      numberbathrooms: 10,
      agreementtype: 'one-year',
      dateavailable: '2021-07-01T00:00:00.000Z',
      petsallowed: 'limited',
      areainfeet: 300,
      furnished: 0,
      laundryinunit: 0,
      laundryinbuilding: 0,
      dishwasher: 0,
      fridgefreezer: 0,
      airconditioning: 0,
      yard: 0,
      balcony: 1,
      smokingpermitted: 2,
      gym: 0,
      pool: 0,
      concierge: 1,
      twentyfourhoursecurity: 1,
      bicycleparking: 0,
      storagelocker: 0,
      elevator: 0,
      wheelchairaccessible: 0,
      braillelabels: 0,
      audioprompts: 0,
      barrierfreeentrancesandramps: 0,
      visualaids: 0,
      accessiblewashroomsinsuite: 0,
      hydro: 0,
      heat: 0,
      water: 1,
      cabletv: 0,
      internet: 0,
      numberparkingspots: 0,
      price: 595,
      location: '5955 25e Avenue, Montréal, QC H1T 3L3, Canada',
      type: 'OFFERED',
      coordinates: [-73.573402, 45.563063],
    },
    url:
      'https://www.kijiji.ca/v-appartement-condo/ville-de-montreal/2-eau-chaude-incluse-dernier-etage-25e-avenue-et-rosemont/1556991276',
  },
  {
    title: '8 1/2 - 3 chambres - Villeray',
    description:
      "8 1/2 non chauffé, boiserie, 3 chambres, bureau, salon, salle à manger, salle d'eau, cuisine, salle ...",
    date: '2021-03-24T18:47:06.000Z',
    image:
      'https://i.ebayimg.com/00/s/NDUwWDgwMA==/z/VosAAOSwlG1gW4nP/$_57.JPG',
    images: [
      'https://i.ebayimg.com/00/s/NDUwWDgwMA==/z/VosAAOSwlG1gW4nP/$_57.JPG',
      'https://i.ebayimg.com/00/s/NDUwWDgwMA==/z/GDMAAOSwjRlgW4nx/$_57.JPG',
      'https://i.ebayimg.com/00/s/NDUwWDgwMA==/z/ULsAAOSwrh9gW4n-/$_57.JPG',
      'https://i.ebayimg.com/00/s/NDUwWDgwMA==/z/B9kAAOSwMIJgW4oa/$_57.JPG',
      'https://i.ebayimg.com/00/s/MzIwWDI0MA==/z/SbYAAOSwVX1gW4os/$_57.JPG',
      'https://i.ebayimg.com/00/s/ODAwWDYwMA==/z/f~4AAOSw4LRgW4o3/$_57.JPG',
      'https://i.ebayimg.com/00/s/ODAwWDYwMA==/z/FMMAAOSwbH1gW4pX/$_57.JPG',
      'https://i.ebayimg.com/00/s/NDUwWDgwMA==/z/aAYAAOSwZKRgW4pd/$_57.JPG',
      'https://i.ebayimg.com/00/s/NDUwWDgwMA==/z/N0AAAOSwRhtgW4ph/$_57.JPG',
      'https://i.ebayimg.com/00/s/NDUwWDgwMA==/z/QIMAAOSwr2FgW4qR/$_57.JPG',
    ],
    attributes: {
      forrentbyhousing: 'ownr',
      unittype: 'apartment',
      numberbedrooms: 5,
      numberbathrooms: 15,
      agreementtype: 'one-year',
      dateavailable: '2021-07-01T00:00:00.000Z',
      petsallowed: 'limited',
      areainfeet: 1550,
      furnished: 0,
      laundryinunit: 0,
      laundryinbuilding: 0,
      dishwasher: 0,
      fridgefreezer: 0,
      airconditioning: 0,
      yard: 0,
      balcony: 1,
      smokingpermitted: 0,
      gym: 0,
      pool: 0,
      concierge: 0,
      twentyfourhoursecurity: 0,
      bicycleparking: 0,
      storagelocker: 0,
      elevator: 0,
      wheelchairaccessible: 0,
      braillelabels: 0,
      audioprompts: 0,
      barrierfreeentrancesandramps: 0,
      visualaids: 0,
      accessiblewashroomsinsuite: 0,
      hydro: 0,
      heat: 0,
      water: 0,
      cabletv: 0,
      internet: 0,
      numberparkingspots: 3,
      price: 2400,
      location: '7839 R. Saint-Gérard, Montréal, QC H2R 2K5, Canada',
      type: 'OFFERED',
      coordinates: [-73.624402, 45.54346],
    },
    url:
      'https://www.kijiji.ca/v-appartement-condo/ville-de-montreal/8-1-2-3-chambres-villeray/1557295840',
  },
  {
    title: '2 Bedroom Apartment / McGill Uni area',
    description:
      'Spacious 2 Bedroom condo in the heart of McGill Ghetto, literally across from University and near ...',
    date: '2021-03-24T18:46:48.000Z',
    image:
      'https://i.ebayimg.com/00/s/NDgwWDY0MA==/z/KZUAAOSwBTVgW4bb/$_57.JPG',
    images: [
      'https://i.ebayimg.com/00/s/NDgwWDY0MA==/z/KZUAAOSwBTVgW4bb/$_57.JPG',
      'https://i.ebayimg.com/00/s/NDgwWDY0MA==/z/0AUAAOSwY~9gW4by/$_57.JPG',
      'https://i.ebayimg.com/00/s/NDgwWDY0MA==/z/krMAAOSwfORgW4b9/$_57.JPG',
      'https://i.ebayimg.com/00/s/NDgwWDY0MA==/z/lEgAAOSwZFNgW4cG/$_57.JPG',
      'https://i.ebayimg.com/00/s/NDgwWDY0MA==/z/tckAAOSwdehgW4cO/$_57.JPG',
    ],
    attributes: {
      forrentbyhousing: 'ownr',
      unittype: 'apartment',
      numberbedrooms: 2.5,
      numberbathrooms: 15,
      agreementtype: 'one-year',
      dateavailable: '2021-06-01T00:00:00.000Z',
      petsallowed: 'limited',
      areainfeet: 1100,
      furnished: 0,
      laundryinunit: 1,
      laundryinbuilding: 0,
      dishwasher: 1,
      fridgefreezer: 1,
      airconditioning: 0,
      yard: 0,
      balcony: 0,
      smokingpermitted: 1,
      gym: 0,
      pool: 0,
      concierge: 0,
      twentyfourhoursecurity: 0,
      bicycleparking: 0,
      storagelocker: 1,
      elevator: 0,
      wheelchairaccessible: 0,
      braillelabels: 0,
      audioprompts: 0,
      barrierfreeentrancesandramps: 0,
      visualaids: 0,
      accessiblewashroomsinsuite: 0,
      hydro: 0,
      heat: 0,
      water: 1,
      cabletv: 0,
      internet: 0,
      numberparkingspots: 0,
      price: 1785,
      location: '3637 University St, H2A 2B3, Montreal, QC',
      type: 'OFFERED',
      coordinates: [-73.592803, 45.560868],
    },
    url:
      'https://www.kijiji.ca/v-appartement-condo/ville-de-montreal/2-bedroom-apartment-mcgill-uni-area/1557295765',
  },
  {
    title: '41/2 for rent with jardin patio metro jolicoeur July',
    description:
      '1644 Boul.Desmarchais Montreal H4E2B4 for juillet Récemment rénovée,2 chambre ferme dans premier ...',
    date: '2021-03-24T18:45:58.000Z',
    image:
      'https://i.ebayimg.com/00/s/NjAwWDgwMA==/z/VuIAAOSw9EpgW4jH/$_57.JPG',
    images: [
      'https://i.ebayimg.com/00/s/NjAwWDgwMA==/z/VuIAAOSw9EpgW4jH/$_57.JPG',
      'https://i.ebayimg.com/00/s/NjAwWDgwMA==/z/GbAAAOSwgQVgW4jK/$_57.JPG',
      'https://i.ebayimg.com/00/s/NjAwWDgwMA==/z/6uwAAOSwartgW4jN/$_57.JPG',
      'https://i.ebayimg.com/00/s/NjAwWDgwMA==/z/aTEAAOSwT95gW4jP/$_57.JPG',
      'https://i.ebayimg.com/00/s/NjAwWDgwMA==/z/2fgAAOSwzw9gW4jR/$_57.JPG',
      'https://i.ebayimg.com/00/s/NjAwWDgwMA==/z/vLQAAOSwPEFgW4jU/$_57.JPG',
      'https://i.ebayimg.com/00/s/NjAwWDgwMA==/z/w6cAAOSw859gW4jW/$_57.JPG',
      'https://i.ebayimg.com/00/s/NjAwWDgwMA==/z/M6sAAOSwFyFgW4jZ/$_57.JPG',
      'https://i.ebayimg.com/00/s/NjAwWDgwMA==/z/OLUAAOSw4o5gW4jc/$_57.JPG',
      'https://i.ebayimg.com/00/s/NjAwWDgwMA==/z/-XAAAOSwRbJgW4je/$_57.JPG',
    ],
    attributes: {
      forrentbyhousing: 'ownr',
      unittype: 'duplex-triplex',
      numberbedrooms: 2,
      numberbathrooms: 10,
      agreementtype: 'one-year',
      dateavailable: '2021-07-01T00:00:00.000Z',
      petsallowed: 'limited',
      areainfeet: 900,
      furnished: 0,
      laundryinunit: 0,
      laundryinbuilding: 0,
      dishwasher: 0,
      fridgefreezer: 0,
      airconditioning: 0,
      yard: 1,
      balcony: 1,
      smokingpermitted: 2,
      gym: 0,
      pool: 0,
      concierge: 0,
      twentyfourhoursecurity: 0,
      bicycleparking: 0,
      storagelocker: 0,
      elevator: 0,
      wheelchairaccessible: 0,
      braillelabels: 0,
      audioprompts: 0,
      barrierfreeentrancesandramps: 0,
      visualaids: 0,
      accessiblewashroomsinsuite: 0,
      hydro: 0,
      heat: 0,
      water: 0,
      cabletv: 0,
      internet: 0,
      numberparkingspots: 0,
      price: 1350,
      location: '1644 Boulevard Desmarchais, Montréal, QC H4E 2B4, Canada',
      type: 'OFFERED',
      coordinates: [-73.586345, 45.455169],
    },
    url:
      'https://www.kijiji.ca/v-appartement-condo/ville-de-montreal/41-2-for-rent-with-jardin-patio-metro-jolicoeur-july/1557295612',
  },
  {
    title: '41/2New condo for rent Ville Saint Laurent- Secteur Bois Franc',
    description:
      'Now 41/2 & 51/2 available !!!! *****SPECIAL PROMOTION for all leases signed on February, 2021 . ...',
    date: '2020-01-20T23:31:22.000Z',
    image:
      'https://i.ebayimg.com/00/s/NDUwWDgwMA==/z/~bgAAOSwipleizbF/$_57.JPG',
    images: [
      'https://i.ebayimg.com/00/s/NDUwWDgwMA==/z/~bgAAOSwipleizbF/$_57.JPG',
      'https://i.ebayimg.com/00/s/NTMzWDgwMA==/z/8pQAAOSw25VeJjcA/$_57.JPG',
      'https://i.ebayimg.com/00/s/NTMzWDgwMA==/z/DIsAAOSwY8teJjdq/$_57.JPG',
      'https://i.ebayimg.com/00/s/NTMzWDgwMA==/z/71oAAOSwAepeJjcN/$_57.JPG',
      'https://i.ebayimg.com/00/s/NTMzWDgwMA==/z/4ZUAAOSwhiJeJjce/$_57.JPG',
      'https://i.ebayimg.com/00/s/NTMzWDgwMA==/z/VzgAAOSwaBJeJjen/$_57.JPG',
      'https://i.ebayimg.com/00/s/NTMzWDgwMA==/z/x9AAAOSwAHFeJjcv/$_57.JPG',
      'https://i.ebayimg.com/00/s/NTMzWDgwMA==/z/nk0AAOSwePReJjb5/$_57.JPG',
      'https://i.ebayimg.com/00/s/NTMzWDgwMA==/z/AIMAAOSwRg9eJjcR/$_57.JPG',
      'https://i.ebayimg.com/00/s/NTMzWDgwMA==/z/SIUAAOSwk8JeJjcq/$_57.JPG',
    ],
    attributes: {
      forrentbyhousing: 'ownr',
      unittype: 'apartment',
      numberbedrooms: 2,
      numberbathrooms: 20,
      agreementtype: 'one-year',
      dateavailable: '2020-12-01T00:00:00.000Z',
      petsallowed: 1,
      areainfeet: 1200,
      furnished: 0,
      laundryinunit: 1,
      laundryinbuilding: 0,
      dishwasher: 1,
      fridgefreezer: 1,
      airconditioning: 1,
      yard: 1,
      balcony: 1,
      smokingpermitted: 1,
      gym: 1,
      pool: 1,
      concierge: 1,
      twentyfourhoursecurity: 1,
      bicycleparking: 0,
      storagelocker: 1,
      elevator: 1,
      wheelchairaccessible: 0,
      braillelabels: 0,
      audioprompts: 0,
      barrierfreeentrancesandramps: 0,
      visualaids: 0,
      accessiblewashroomsinsuite: 0,
      hydro: 1,
      heat: 1,
      water: 1,
      cabletv: 0,
      internet: 1,
      numberparkingspots: 0,
      location:
        '1300 Boulevard Alexis-Nihon, Saint-Laurent, QC H4R 2K8, Canada',
      type: 'OFFERED',
      coordinates: [-73.697065, 45.508846],
    },
    url:
      'https://www.kijiji.ca/v-appartement-condo/ville-de-montreal/41-2new-condo-for-rent-ville-saint-laurent-secteur-bois-franc/1483457704',
  },
]
